services:
  # BASE DE DONNÉES
  postgres:
    image: postgres:15
    container_name: csgo_postgres
    restart: always
    environment:
      POSTGRES_USER: csgo_user
      POSTGRES_PASSWORD: csgo_pass
      POSTGRES_DB: csgo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - csgo_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U csgo_user -d csgo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # VISUALISATION
  metabase:
    image: metabase/metabase:latest
    container_name: csgo_metabase
    ports:
      - "8080:3000"
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - csgo_network

  # GESTION DES LOGS (Atelier 3 - Étape 3)
  dozzle:
    image: amir20/dozzle:latest
    container_name: csgo_logs
    ports:
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - csgo_network

volumes:
  postgres_data:

networks:
  csgo_network:
    driver: bridge